# Generated by Django 5.2.7 on 2026-01-27 01:23

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('location_address', models.CharField(max_length=255, verbose_name='Địa chỉ')),
                ('google_map_link', models.URLField(blank=True, verbose_name='Link Google Map')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Đánh giá (Sao)')),
                ('avg_price', models.PositiveIntegerField(help_text='Giá trung bình VND', verbose_name='Giá trung bình')),
                ('cover_image', models.ImageField(upload_to='food/', verbose_name='Ảnh đại diện')),
            ],
            options={
                'verbose_name': 'Review Ăn uống (Zone 2)',
                'verbose_name_plural': 'Pantry Reviews',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán')),
                ('affiliate_link', models.URLField(verbose_name='Link mua hàng (Affiliate)')),
                ('platform', models.CharField(choices=[('SHOPEE', 'Shopee'), ('LAZADA', 'Lazada'), ('TIKI', 'Tiki'), ('OTHER', 'Khác')], default='SHOPEE', max_length=20)),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ảnh sản phẩm')),
            ],
            options={
                'verbose_name': 'Sản phẩm (Zone 4)',
                'verbose_name_plural': 'Shop Decor',
            },
        ),
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên phần quà')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='rewards/', verbose_name='Ảnh quà')),
                ('point_cost', models.PositiveIntegerField(verbose_name='Điểm cần đổi')),
                ('stock', models.PositiveIntegerField(default=10, verbose_name='Số lượng còn lại')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_code', models.CharField(choices=[('ZONE_1', 'Bàn Làm Việc'), ('ZONE_2', 'Pantry & Health'), ('ZONE_3', 'Góc Trà Đá'), ('ZONE_4', 'Shop Decor')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('icon_name', models.CharField(help_text='Tên icon Lucide (vd: coffee, briefcase)', max_length=50)),
                ('color_class', models.CharField(help_text='Tailwind class (vd: bg-blue-50)', max_length=50)),
                ('priority_morning', models.IntegerField(default=0, verbose_name='Thứ tự Sáng')),
                ('priority_work', models.IntegerField(default=0, verbose_name='Thứ tự Giờ làm')),
                ('priority_lunch', models.IntegerField(default=0, verbose_name='Thứ tự Trưa')),
                ('priority_chill', models.IntegerField(default=0, verbose_name='Thứ tự Chiều/Tối')),
            ],
        ),
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('content', models.TextField(verbose_name='Nội dung tâm sự')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='Chế độ ẩn danh')),
                ('pseudonym', models.CharField(max_length=100, verbose_name='Bút danh hiển thị')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối')], db_index=True, default='PENDING', max_length=20)),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Lượt tim')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Lượt bình luận')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tác giả thực (Ẩn)')),
            ],
            options={
                'verbose_name': 'Confession (Zone 3)',
                'verbose_name_plural': 'Danh sách Confessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.confession')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='URL Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả tài liệu')),
                ('file_upload', models.FileField(upload_to=core.models.get_file_path, verbose_name='File đính kèm')),
                ('file_type', models.CharField(choices=[('PPT', 'PowerPoint'), ('XLS', 'Excel'), ('DOC', 'Word/PDF'), ('VECTOR', 'Design Vector')], default='DOC', max_length=10)),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Lượt tải')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người upload')),
            ],
            options={
                'verbose_name': 'Tài liệu (Zone 1)',
                'verbose_name_plural': 'Kho Tài liệu',
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('LOGIN', 'Điểm danh hàng ngày'), ('UPLOAD', 'Tải lên tài liệu'), ('POST', 'Viết bài/Review'), ('REDEEM', 'Đổi quà')], max_length=20)),
                ('amount', models.IntegerField(verbose_name='Số điểm (+/-)')),
                ('description', models.CharField(max_length=255, verbose_name='Mô tả chi tiết')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Chức danh')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='Công ty')),
                ('total_kpi_points', models.IntegerField(db_index=True, default=0, verbose_name='Tổng điểm KPI')),
                ('level_rank', models.CharField(default='Intern', max_length=50, verbose_name='Cấp bậc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
