# Generated by Django 5.2.7 on 2026-01-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_parent_confession_angry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='confession',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Công ty liên quan'),
        ),
    ]
