# Generated by Django 5.2.7 on 2026-01-27 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_confession_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên quán')),
                ('address', models.CharField(max_length=300, verbose_name='Địa chỉ')),
                ('image', models.ImageField(upload_to='restaurants/', verbose_name='Ảnh đại diện')),
                ('rating', models.FloatField(default=0.0, verbose_name='Điểm đánh giá')),
                ('review_count', models.IntegerField(default=0, verbose_name='Số review')),
                ('category', models.CharField(max_length=100, verbose_name='Loại hình (Cơm, Phở...)')),
                ('url_foody', models.URLField(blank=True, null=True, verbose_name='Link Foody (nếu có)')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên món')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='core.restaurant')),
            ],
        ),
    ]
