# Generated by Django 5.2.7 on 2026-01-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restaurant_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('yoga', 'Cổ Vai Gáy'), ('wrist', 'Cổ Tay'), ('meditation', 'Thiền'), ('music', 'Nhạc Focus')], max_length=20, unique=True, verbose_name='Mã bài tập')),
                ('title', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('youtube_id', models.CharField(max_length=50, verbose_name='ID Youtube')),
                ('duration', models.IntegerField(default=300, verbose_name='Thời gian tập (giây)')),
            ],
        ),
    ]
