# Generated by Django 5.2.7 on 2026-01-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_healthexercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='Món ngon', max_length=100, verbose_name='Loại hình (Cơm, Phở...)'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=5.0, verbose_name='Điểm đánh giá'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='review_count',
            field=models.IntegerField(default=1, verbose_name='Số review'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='url_foody',
            field=models.URLField(blank=True, null=True, verbose_name='Link App'),
        ),
    ]
