# Generated by Django 5.2.7 on 2026-01-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dish_name_alter_restaurant_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Confession'},
        ),
        migrations.AlterModelOptions(
            name='documentresource',
            options={'verbose_name': 'Tài liệu', 'verbose_name_plural': 'Kho Tài liệu'},
        ),
        migrations.AlterModelOptions(
            name='foodreview',
            options={'verbose_name': 'Review Ăn uống'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Shop Decor'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='confession',
            name='angry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='confession',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='confession',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='confession',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='confession',
            name='loves_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên món'),
        ),
        migrations.AlterField(
            model_name='foodreview',
            name='avg_price',
            field=models.PositiveIntegerField(verbose_name='Giá trung bình'),
        ),
        migrations.AlterField(
            model_name='foodreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'Hệ thống'), ('WARNING', 'Cảnh báo'), ('SUCCESS', 'Tin vui')], default='SYSTEM', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='affiliate_link',
            field=models.URLField(verbose_name='Link mua hàng'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(default='Món ngon', max_length=100, verbose_name='Loại hình'),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='color_class',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='display_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='icon_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='priority_chill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='priority_lunch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='priority_morning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='priority_work',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zoneconfig',
            name='zone_code',
            field=models.CharField(choices=[('ZONE_1', 'Bàn Làm Việc'), ('ZONE_2', 'Pantry'), ('ZONE_3', 'Confession'), ('ZONE_4', 'Shop')], max_length=20, unique=True),
        ),
    ]
