# Generated by Django 5.2.7 on 2026-01-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_options_remove_product_affiliate_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Đang kinh doanh'),
        ),
    ]
