# Generated by Django 5.2.7 on 2026-01-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(default='Sếp ẩn danh', max_length=100)),
                ('time_category', models.CharField(choices=[('morning', 'Buổi Sáng'), ('lunch', 'Buổi Trưa'), ('work', 'Giờ Làm Việc'), ('chill', 'Cuối Ngày/Tối')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
