# Generated by Django 5.2.7 on 2026-01-28 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dailyquote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoneConfig',
        ),
    ]
