# Generated by Django 5.2.7 on 2026-01-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_zoneconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_hot',
        ),
        migrations.RemoveField(
            model_name='product',
            name='platform',
        ),
        migrations.AlterField(
            model_name='product',
            name='affiliate_url',
            field=models.URLField(default='https://shopee.com', max_length=500, verbose_name='Link Affiliate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Sản Phẩm', max_length=200, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_display',
            field=models.CharField(default='Liên hệ', max_length=50, verbose_name='Giá hiển thị'),
        ),
    ]
